"""

A module that initializes and includes the agent testing framework components.

This module imports the classes provided by the Agent testing framework which is responsible for running test cases against an AI agent to evaluate its performance. The testing framework allows for defining various test cases with specific prompts and expected outcomes, along with a suite that can run multiple test cases and aggregate their results.

Classes:
    AgentTestCaseOutcome (Enum): An enumeration of possible outcomes for a test case, representing success, error, unknown, or inconclusive results.
    AgentTestCaseResult: Encapsulates the outcome of a single test case execution including the test prompt, actual result, execution time, and scores generated by the applied scorers, along with any errors encountered.
    AgentTestCase: Represents a single test case with a defined prompt and a list of scorers used to evaluate the agent's response.
    AgentTestSuiteResult: Collects the results of all the test cases executed as part of a test suite.
    AgentTestSuite: Encapsulates a collection of test cases that can be run against an agent, offering methods to add test cases individually and execute the entire suite, optionally displaying a progress bar.


"""
from .agent_tests import AgentTestCaseOutcome, AgentTestCaseResult, AgentTestCase, AgentTestSuiteResult, AgentTestSuite
