"""

Module for evaluator hierarchy and exception handling within an agent system.

This module defines a set of classes used to evaluate actions, responses, or
messages generated by agents within a system that involves interaction with end-users
or other agents. Evaluation is critical to ensure the quality and correctness of agent
outputs.

Classes:
    EvaluatorException: A custom exception class for evaluator-related errors.
    EvaluatorBase: An abstract base class establishing the interface and common
        functionality for all evaluator classes that inherit from it.
    BasicEvaluator: A concrete implementation of EvaluatorBase designed to perform
        simple evaluation tasks.
    LLMEvaluator: A specialized evaluator inheriting from EvaluatorBase, which uses a
        Language Model (LLM) for evaluating responses.

This module also contains imports that make the evaluator classes accessible under the
module's namespace.


"""

from .evaluator_base import EvaluatorException, EvaluatorBase
from .basic_evaluator import BasicEvaluator
from .llm_evaluator import LLMEvaluator
