from typing import List, Optional, Any

### CLASSEs

class GoogleNews:
    def __init__(
        self,
        lang: str = ...,
        period: str = ...,
        start: str = ...,
        end: str = ...,
        encode: str = ...,
        region: Optional[str] = ...,
    ): ...
    def getVersion(self) -> str: ...
    def enableException(self, enable: bool = ...): ...
    def set_lang(self, lang: str): ...
    def setlang(self, lang: str): ...
    def set_period(self, period: str): ...
    def setperiod(self, period: str): ...
    def set_time_range(self, start: str, end: str): ...
    def setTimeRange(self, start: str, end: str): ...
    def set_encode(self, encode: str): ...
    def setencode(self, encode: str): ...
    def search(self, key: str): ...
    def build_response(self): ...
    def page_at(self, page: int = ...) -> List[Any]: ...
    def get_page(self, page: int = ...) -> List[Any]: ...
    def getpage(self, page: int = ...) -> List[Any]: ...
    def get_news(self, key: str = ..., deamplify: bool = ...): ...
    def total_count(self) -> int: ...
    def result(self, sort: bool = ...) -> List[Any]: ...
    def results(self, sort: bool = ...) -> List[Any]: ...
    def get_texts(self) -> List[str]: ...
    def gettext(self) -> List[str]: ...
    def get_links(self) -> List[str]: ...
    def clear(self): ...
